version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build: 
    commands:
      - echo nothing here
  build:
    commands:
      - echo build started on `Date`
      - mvn clean install
  post_build:
    commands:
       - echo build completed on `Date`
       - cd /root/.m2/repository/com/hcl/hackathon/fullstack/FullStackApplication/0.0.1-SNAPSHOT/
artifacts:
  files:
    - FullStackApplication-0.0.1-SNAPSHOT.jar
cache:
  paths:
    -'root/.m2/**/*'