version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build: 
    commands:
      - echo nothing here
  build:
    commands:
      - echo build started on `Date`
      - mvn clean install
  post_build:
    commands:
       - echo build completed on `Date`
artifacts:
  files:
    - /target
cache:
  paths:
    -'root/.m2/**/*'