drop table if exists room_amenities;
drop table if exists booked_slot;
drop table if exists time_slot;
drop table if exists amenity;
drop table if exists room;
drop table if exists location;
create table amenity (amenity_id integer not null AUTO_INCREMENT, feature varchar(255), name varchar(255), primary key (amenity_id));
create table location (location_id integer not null AUTO_INCREMENT, building_name varchar(255), city varchar(255), floor integer not null, primary key (location_id));
create table room (room_id integer not null AUTO_INCREMENT, description varchar(255), room_name varchar(255), maxOccupancy integer, location_location_id integer, primary key (room_id));
create table room_amenities (room_room_id integer not null, amenities_amenity_id integer not null, primary key (room_room_id,amenities_amenity_id) );
create table booked_slot (booked_slot_id integer not null AUTO_INCREMENT, room_id integer, time_slot_id integer, primary key (booked_slot_id));
create table time_slot (time_slot_id integer not null AUTO_INCREMENT, date date, end_time time, start_time time, primary key (time_slot_id));
alter table room add constraint FKj7u49d85fx2vn44lhpk922o3y foreign key (location_location_id) references location(location_id);
alter table room_amenities add constraint FKg01t3ru2a1d6d14392idycd9b foreign key (amenities_amenity_id) references amenity(amenity_id);
alter table room_amenities add constraint FKjegxdm4kmpqqqae3jqb46mwti foreign key (room_room_id) references room(room_id);
alter table booked_slot add constraint FK5xrcmblavdk967ledjatv7hxd foreign key (room_id) references room(room_id);
alter table booked_slot add constraint FKmx1p1fdqs9c9yexodaf8enrps foreign key (time_slot_id) references time_slot(time_slot_id);