drop table amenity if exists;
drop table location if exists;
drop table room if exists;
drop table room_amenities if exists;
drop table booked_slot if exists;
drop table time_slot if exists;
drop sequence hibernate_sequence if exists;
create sequence hibernate_sequence start with 1 increment by 1;
create table amenity (amenity_id integer not null, feature varchar(255), name varchar(255), primary key (amenity_id));
create table location (location_id integer not null, building_name varchar(255), city varchar(255), floor integer not null, primary key (location_id));
create table room (room_id integer not null, description varchar(255), room_name varchar(255), maxOccupancy integer, location_location_id integer, primary key (room_id));
create table room_amenities (room_room_id integer not null, amenities_amenity_id integer not null);
create table booked_slot (booked_slot_id integer not null, room_id integer, time_slot_id integer, primary key (booked_slot_id));
create table time_slot (time_slot_id integer not null, date date, end_time time, start_time time, primary key (time_slot_id));
alter table room_amenities add constraint UK_2hnd878okocvnas5oqrcotvie unique (amenities_amenity_id);
alter table room add constraint FKj7u49d85fx2vn44lhpk922o3y foreign key (location_location_id) references location;
alter table room_amenities add constraint FKg01t3ru2a1d6d14392idycd9b foreign key (amenities_amenity_id) references amenity;
alter table room_amenities add constraint FKjegxdm4kmpqqqae3jqb46mwti foreign key (room_room_id) references room;
alter table booked_slot add constraint FK5xrcmblavdk967ledjatv7hxd foreign key (room_id) references room;
alter table booked_slot add constraint FKmx1p1fdqs9c9yexodaf8enrps foreign key (time_slot_id) references time_slot;